### DISCUSSION TITLE
有没有朋友帮忙看一下，DNS解析经常会出现类似的错误，这个正常吗？

### DISCUSSION THREAD

**Discussion by easyinplay** [libnyanpasu/clash-nyanpasu#1430] [Q&A]
![image](https://github.com/user-attachments/assets/93b79526-41de-4529-94cc-163ea377649a)
[2024-08-26-log.zip](https://github.com/user-attachments/files/16743260/2024-08-26-log.zip)

附一下我的DNS配置：

```
# DNS配置
dns:
  cache-algorithm: arc
  enable: true # 关闭将使用系统 DNS
  prefer-h3: true # 开启 DoH 支持 HTTP/3，将并发尝试
  listen: ':53' # 开启 DNS 服务器监听,，仅支持 udp
  ipv6: false # false 将返回 AAAA 的空结果
  ipv6-timeout: 300 # 单位：ms，内部双栈并发时，向上游查询 AAAA 时，等待 AAAA 的时间，默认 100ms

  # 用于解析 nameserver，fallback 以及其他DNS服务器配置的，DNS 服务域名
  # 只能使用纯 IP 地址，可使用加密 DNS
  default-nameserver:
    # ipv4 dns
    - https://1.12.12.12/dns-query # DNSPod DNS+腾讯DNS
    - https://120.53.53.53/dns-query # DNSPod DNS+腾讯DNS
    - https://223.5.5.5/dns-query # 阿里AliDNS 从2024.09.30开始限速
    - https://223.6.6.6/dns-query # 阿里AliDNS 从2024.09.30开始限速   
    - https://1.1.1.1/dns-query # Cloudflare
    - https://1.0.0.1/dns-query # Cloudflare    
    - https://45.11.45.11/dns-query # DNS.SB 服务器位于国外，但延迟使用体检较为可观，支持 EDNS-Client-Subnet
    - https://185.222.222.222/dns-query # DNS.SB 服务器位于国外，但延迟使用体检较为可观，支持 EDNS-Client-Subnet
    - https://8.8.8.8/dns-query #Google DNS
    - https://8.8.4.4/dns-query #Google DNS
    # ipv6 dns    
    # - https://[2400:3200::1]/dns-query # 阿里 IPv6 DNS 从2024.09.30开始限速
    # - https://[2400:3200:baba::1]/dns-query # 阿里 IPv6 DNS 从2024.09.30开始限速
    # - tls://[2a09::]:853 # DNS.SB 服务器位于国外，但延迟使用体检较为可观，支持 EDNS-Client-Subnet
    # - tls://[2a11::]:853 # DNS.SB 服务器位于国外，但延迟使用体检较为可观，支持 EDNS-Client-Subnet
    # - https://[2001:4860:4860::64]/dns-query #Google IPV6 DNS
    # - https://[2001:4860:4860::6464]/dns-query #Google IPV6 DNS
    # - https://[2606:4700:4700::1111]/dns-query # Cloudflare
    # - https://[2606:4700:4700::1001]/dns-query # Cloudflare
    # - https://[2606:4700:4700::64]/dns-query # Cloudflare
    # - https://[2606:4700:4700::6464]/dns-query # Cloudflare
    # 系统dns
    # - system # append DNS server from system configuration. If not found, it would print an error log and skip.
  enhanced-mode: fake-ip # or fake-ip or redir-host
  fake-ip-range: 198.18.0.1/16 # fake-ip 池设置,tun 的默认 IPV4 地址 也使用此值作为参考
  # Hostnames in this list will not be resolved with fake IPs
  # i.e. questions to these domain names will always be answered with their
  # real IP addresses
  # 将常见国内域名加入到 fake-ip-filter 中，这里推荐一个每日更新国内域名的项目：felixonmars/dnsmasq-china-list，你可以自行下载 accelerated-domains.china.conf 文件并为其中的域名加上 +. 前缀然后添加到 fake-ip-filter 中
  fake-ip-filter: # fakeip 过滤，以下地址不会下发 fakeip 映射用于连接
    # === LAN ===   
    - "*.lan"
    - "*.local"
    - "*.cn"
    # === NTP Service ===
    - "time.*.com"
    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'
    - "time.*.gov"
    - "time.*.edu.cn"
    - "time.*.apple.com"
    - 'ntp.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'
    - "*.time.edu.cn"
    - "ntp.*.edu.cn"
    - "ntp.tuna.tsinghua.edu.cn"
    - "*.ntp.org.cn"
    - "ntp.ntsc.ac.cn"
    - "+.pool.ntp.org"
    - "time1.cloud.tencent.com" 
    # === Windows 10 Connnect Detection ===
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    # Stun Services
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*.*.*"
    # === Linksys Wireless Router ===
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    # === apple Software Update Service ===
    - 'swscan.apple.com'
    - 'mesu.apple.com'
    # === Music Service ===
    ## NetEase
    - '+.music.163.com'
    - '*.126.net'
    ## baidu
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    ## Kugou
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    ## Kuwo
    - '*.kuwo.cn'
    ## JOOX
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    ## QQ
    - '+.y.qq.com'
    - '+.music.tc.qq.com'
    - 'aqqmusic.tc.qq.com'
    - '+.stream.qqmusic.qq.com'
    ## Xiami
    - '*.xiami.com'
    ## Migu
    - '+.music.migu.cn'
    # === Game Service ===
    ## nintendo Switch
    - '+.srv.nintendo.net'
    ## Sony PlayStation
    - '+.stun.playstation.net'
    ## microsoft Xbox
    - 'xbox.*.microsoft.com'
    - '+.xboxlive.com'
    - '+.xboxlive.cn'
    # === Other ===
    ## QQ Quick Login
    - 'localhost.ptlogin2.qq.com'
    ## Golang
    - 'proxy.golang.org'
    ## STUN Server
    - 'stun.*.*'
    - 'stun.*.*.*'
    # bilibili CDN
    - "+.mcdn.bilivideo.cn"
    ## CMCC
    - "*.cmpassport.com"
    - "*.jegotrip.com.cn"
    # proxy
    - "+.jjcruises.com"
    - "+.gfwladder.com"
  
  respect-rules: true # dns 连接跟随 rules，需配置 proxy-server-nameserver
  
  # 专用于节点域名解析的 DNS 服务器，非必要配置项
  # 配置服务器若查询失败将使用 nameserver，非并发查询
  proxy-server-nameserver:
    # ipv4 dns 用来解析国内域名的dns，对dns污染不敏感的网站
    - https://doh.pub/dns-query # DNSPod DNS+腾讯DNS  存在污染
    - https://doh.360.cn/dns-query # 360DNS    存在污染
    - https://dns.cfiec.net/dns-query
    - https://rubyfish.cn/dns-query   # 红鱼rubyfish DNS 国内上游 额外的威胁网址过滤能力       
    # ipv4 dns 国内能用且没有污染的dns      
    - https://dns.rubyfish.cn/dns-query # 红鱼rubyfish DNS  国外上游   
    - https://i.233py.com/dns-query # GEEKDNS 国内    
    - quic://cn-east.ovo.glass  # iQDNS 华东高防 BGP 节点
    - quic://cn-south.iqiqzz.com # iQDNS 华南高防 BGP 节点
    - https://cn-east.iqiqzz.com/dns-query # iQDNS 华东高防 BGP 节点
    - https://cn-south.iqiqzz.com/dns-query # iQDNS 华南高防 BGP 节点
    - https://doh.apad.pro/cn-query
    - https://doh.apad.pro/dns-query # apad.pro
    - https://doh.18bit.cn/dns-query
    # ipv6 dns
    # - https://dns.ipv6dns.com/dns-query # 北京天地互连 IPV6 公共 DNS
    # - https://v6.rubyfish.cn/dns-query # 红鱼rubyfish IPV6 DNS
    # - https://dns11.quad9.net/dns-query # IBM Quad9 ipv4+ipv6
    # - tls://[2a09::]:853 # DNS.SB 服务器位于国外，但延迟使用体检较为可观，支持 EDNS-Client-Subnet
    # - tls://[2a11::]:853 # DNS.SB 服务器位于国外，但延迟使用体检较为可观，支持 EDNS-Client-Subnet

  # DNS主要域名配置,默认的域名解析服务器，如不配置 fallback/proxy-server-nameserver , 则所有域名都由 nameserver 解析
  # 支持 UDP，TCP，DoT，DoH，DoQ
  # 这部分为主要 DNS 配置，影响所有直连，确保使用对大陆解析精准的 DNS
  nameserver: 
    # ipv4 dns 用来解析国内域名的dns，对dns污染不敏感的网站
    - https://doh.pub/dns-query # DNSPod DNS+腾讯DNS  存在污染
    - https://doh.360.cn/dns-query # 360DNS 存在污染
    - https://dns.cfiec.net/dns-query
    - https://rubyfish.cn/dns-query   # 红鱼rubyfish DNS 国内上游 额外的威胁网址过滤能力 
    # 国内能用且没有污染的dns      
    - https://dns.rubyfish.cn/dns-query # 红鱼rubyfish DNS  国外上游   
    - https://i.233py.com/dns-query # GEEKDNS 国内    
    - quic://cn-east.ovo.glass  # iQDNS 华东高防 BGP 节点
    - quic://cn-south.iqiqzz.com # iQDNS 华南高防 BGP 节点
    - https://cn-east.iqiqzz.com/dns-query # iQDNS 华东高防 BGP 节点
    - https://cn-south.iqiqzz.com/dns-query # iQDNS 华南高防 BGP 节点
    - https://doh.apad.pro/cn-query
    - https://doh.apad.pro/dns-query # apad.pro
    - https://doh.18bit.cn/dns-query # 18bit DNS
    # 用来解析国外域名的dns，很多国内直接访问是有问题的
    - https://dns.233py.com/dns-query # GEEKDNS 国外
    - https://dns.twnic.tw/dns-query # TWNIC Quad 101
    - https://public.dns.iij.jp/dns-query # 日本 IIJ DNS
    - https://doh-jp.blahdns.com/dns-query # 日本 Blahdns
    - https://doh.dns.sb/dns-query # DNS.SB 服务器位于国外，但延迟使用体检较为可观，支持 EDNS-Client-Subnet
    - quic://dns-unfiltered.adguard.com # AdGuard DNS
    - https://dns.cloudflare.com/dns-query # Cloudflare 公共DNS 国外
    - https://dns.google/dns-query # Google DNS
    - https://dns11.quad9.net/dns-query # IBM Quad9
    - https://doh.opendns.com/dns-query # OpenDNS
    - https://doh.powerdns.org # PowerDNS
    - https://dns.switch.ch/dns-quer #switch dns
    - https://private.canadianshield.cira.ca/dns-query #CIRA Canadian Shield DNS
    - https://all.dns.mullvad.net/dns-query # Mullvad Public DNS
    # ipv6 dns
    # - https://v6.rubyfish.cn/dns-query # 红鱼rubyfish IPV6 DNS
    - https://dns11.quad9.net/dns-query # IBM Quad9 ipv4+ipv6
    # - tls://[2a09::]:853 # DNS.SB 服务器位于国外，但延迟使用体检较为可观，支持 EDNS-Client-Subnet
    # - tls://[2a11::]:853 # DNS.SB 服务器位于国外，但延迟使用体检较为可观，支持 EDNS-Client-Subnet
    # - https://[2001:4860:4860::64]/dns-query #Google IPV6 DNS
    # - https://[2001:4860:4860::6464]/dns-query #Google IPV6 DNS
    # - https://[2606:4700:4700::1111]/dns-query # Cloudflare
    # - https://[2606:4700:4700::1001]/dns-query # Cloudflare
    # - https://[2606:4700:4700::64]/dns-query # Cloudflare
    # - https://[2606:4700:4700::6464]/dns-query # Cloudflare      
    # - dhcp://en0 # dns from dhcp
    # - '8.8.8.8#en0' # 兼容指定 DNS 出口网卡

  # 指定域名查询的解析服务器，可使用 geosite, 优先于 nameserver/fallback 查询
  nameserver-policy:
    '+.msftconnecttest.com,+.msftncsi.com': 
      - https://doh.pub/dns-query # DNSPod DNS+腾讯DNS  存在污染
    "+.baidu.com,+.google.cn":
      - https://doh.onedns.net/dns-query # OneDNS拦截版
    "+.twitter.com,+.facebook.com,+.youtube.com,+.google.com": 
      - quic://dns.adguard.com
      - https://doh.libredns.gr/ads
      - https://adblock.doh.mullvad.net/dns-query
    "+.abchina.com,+.ccb.com,+.jd.com,+.taobao.com,+.tmall.com,+.weixin.com,+.alipay.com": 
      - https://doh.360.cn/dns-query
    "+.paypal.com": 
      - https://doh.cleanbrowsing.org/doh/security-filter/
      - https://security.cloudflare-dns.com/dns-query
    # '+.internal.crop.com':'10.0.0.1'
    '+.googlesyndication.com': 
      - https://dns.cloudflare.com/dns-query # Cloudflare 公共DNS 国外
      - https://dns.google/dns-query # Google DNS
    'geosite:category-ads-all': 127.0.0.1
    'geosite:private,apple-cn,apple@cn,google-cn,category-games@cn,tld-cn,cn,googlefcm':
      # ipv4 dns 用来解析国内域名的dns，对dns污染不敏感的网站
      - https://doh.pub/dns-query # DNSPod DNS+腾讯DNS  存在污染
      - https://doh.360.cn/dns-query # 360DNS    存在污染
      - https://dns.cfiec.net/dns-query
      - https://rubyfish.cn/dns-query   # 红鱼rubyfish DNS 国内上游 额外的威胁网址过滤能力   
      # ipv4 dns 国内能用且没有污染的dns      
      - https://dns.rubyfish.cn/dns-query # 红鱼rubyfish DNS  国外上游   
      - https://i.233py.com/dns-query # GEEKDNS 国内    
      - quic://cn-east.ovo.glass  # iQDNS 华东高防 BGP 节点
      - quic://cn-south.iqiqzz.com # iQDNS 华南高防 BGP 节点
      - https://cn-east.iqiqzz.com/dns-query # iQDNS 华东高防 BGP 节点
      - https://cn-south.iqiqzz.com/dns-query # iQDNS 华南高防 BGP 节点
      - https://doh.apad.pro/cn-query
      - https://doh.apad.pro/dns-query # apad.pro
      - https://doh.18bit.cn/dns-query
      # ipv6 dns
      # - https://dns.ipv6dns.com/dns-query # 北京天地互连 IPV6 公共 DNS
      # - https://v6.rubyfish.cn/dns-query # 红鱼rubyfish IPV6 DNS
      - https://dns11.quad9.net/dns-query # IBM Quad9 ipv4+ipv6
      # - https://[2400:3200::1]/dns-query # 阿里 IPv6 DNS
      # - https://[2400:3200:baba::1]/dns-query # 阿里 IPv6 DNS
      # - tls://[2a09::]:853 # DNS.SB 服务器位于国外，但延迟使用体检较为可观，支持 EDNS-Client-Subnet
      # - tls://[2a11::]:853 # DNS.SB 服务器位于国外，但延迟使用体检较为可观，支持 EDNS-Client-Subnet
    # 'geosite:netflix,disney':
    #   # sni反代
    #   - 127.0.0.1           
    # gfw 域名直接走境外 dns，避免使用 nameserver & fallback 的机制产生 dns 泄露
    'geosite:gfw,greatfire,geolocation-!cn':
      # 用来解析国外域名的dns，很多国内直接访问是有问题的
      # 国内能用且没有污染的dns      
      - https://dns.rubyfish.cn/dns-query # 红鱼rubyfish DNS  国外上游   
      - https://i.233py.com/dns-query # GEEKDNS 国内    
      - quic://cn-east.ovo.glass  # iQDNS 华东高防 BGP 节点
      - quic://cn-south.iqiqzz.com # iQDNS 华南高防 BGP 节点
      - https://cn-east.iqiqzz.com/dns-query # iQDNS 华东高防 BGP 节点
      - https://cn-south.iqiqzz.com/dns-query # iQDNS 华南高防 BGP 节点
      - https://doh.apad.pro/cn-query
      - https://doh.apad.pro/dns-query # apad.pro
      - https://doh.18bit.cn/dns-query # 18bit DNS
      # 用来解析国外域名的dns，很多国内直接访问是有问题的
      - https://dns.233py.com/dns-query # GEEKDNS 国外
      - https://dns.twnic.tw/dns-query # TWNIC Quad 101
      - https://public.dns.iij.jp/dns-query # 日本 IIJ DNS
      - https://doh-jp.blahdns.com/dns-query # 日本 Blahdns
      - https://doh.dns.sb/dns-query # DNS.SB 服务器位于国外，但延迟使用体检较为可观，支持 EDNS-Client-Subnet
      - quic://dns-unfiltered.adguard.com # AdGuard DNS
      - https://dns.cloudflare.com/dns-query # Cloudflare 公共DNS 国外
      - https://dns.google/dns-query # Google DNS
      - https://dns11.quad9.net/dns-query # IBM Quad9
      - https://doh.opendns.com/dns-query # OpenDNS
      - https://doh.powerdns.org # PowerDNS
      - https://dns.switch.ch/dns-quer #switch dns
      - https://private.canadianshield.cira.ca/dns-query #CIRA Canadian Shield DNS
      - https://all.dns.mullvad.net/dns-query # Mullvad Public DNS
      # ipv6 dns
      # - https://v6.rubyfish.cn/dns-query # 红鱼rubyfish IPV6 DNS
      - https://dns11.quad9.net/dns-query # IBM Quad9 ipv4+ipv6
      # - tls://[2a09::]:853 # DNS.SB 服务器位于国外，但延迟使用体检较为可观，支持 EDNS-Client-Subnet
      # - tls://[2a11::]:853 # DNS.SB 服务器位于国外，但延迟使用体检较为可观，支持 EDNS-Client-Subnet
      # - https://[2001:4860:4860::64]/dns-query #Google IPV6 DNS
      # - https://[2001:4860:4860::6464]/dns-query #Google IPV6 DNS
      # - https://[2606:4700:4700::1111]/dns-query # Cloudflare
      # - https://[2606:4700:4700::1001]/dns-query # Cloudflare
      # - https://[2606:4700:4700::64]/dns-query # Cloudflare
      # - https://[2606:4700:4700::6464]/dns-query # Cloudflare 
    'geoip:!cn':
      # 用来解析国外域名的dns，很多国内直接访问是有问题的
      # 国内能用且没有污染的dns      
      - https://dns.rubyfish.cn/dns-query # 红鱼rubyfish DNS  国外上游   
      - https://i.233py.com/dns-query # GEEKDNS 国内    
      - quic://cn-east.ovo.glass  # iQDNS 华东高防 BGP 节点
      - quic://cn-south.iqiqzz.com # iQDNS 华南高防 BGP 节点
      - https://cn-east.iqiqzz.com/dns-query # iQDNS 华东高防 BGP 节点
      - https://cn-south.iqiqzz.com/dns-query # iQDNS 华南高防 BGP 节点
      - https://doh.apad.pro/cn-query
      - https://doh.apad.pro/dns-query # apad.pro
      - https://doh.18bit.cn/dns-query # 18bit DNS
      # 用来解析国外域名的dns，很多国内直接访问是有问题的
      - https://dns.233py.com/dns-query # GEEKDNS 国外
      - https://dns.twnic.tw/dns-query # TWNIC Quad 101
      - https://public.dns.iij.jp/dns-query # 日本 IIJ DNS
      - https://doh-jp.blahdns.com/dns-query # 日本 Blahdns
      - https://doh.dns.sb/dns-query # DNS.SB 服务器位于国外，但延迟使用体检较为可观，支持 EDNS-Client-Subnet
      - quic://dns-unfiltered.adguard.com # AdGuard DNS
      - https://dns.cloudflare.com/dns-query # Cloudflare 公共DNS 国外
      - https://dns.google/dns-query # Google DNS
      - https://dns11.quad9.net/dns-query # IBM Quad9
      - https://doh.opendns.com/dns-query # OpenDNS
      - https://doh.powerdns.org # PowerDNS
      - https://dns.switch.ch/dns-quer #switch dns
      - https://private.canadianshield.cira.ca/dns-query #CIRA Canadian Shield DNS
      - https://all.dns.mullvad.net/dns-query # Mullvad Public DNS
      # ipv6 dns
      # - https://v6.rubyfish.cn/dns-query # 红鱼rubyfish IPV6 DNS
      - https://dns11.quad9.net/dns-query # IBM Quad9 ipv4+ipv6
      # - tls://[2a09::]:853 # DNS.SB 服务器位于国外，但延迟使用体检较为可观，支持 EDNS-Client-Subnet
      # - tls://[2a11::]:853 # DNS.SB 服务器位于国外，但延迟使用体检较为可观，支持 EDNS-Client-Subnet
      # - https://[2001:4860:4860::64]/dns-query #Google IPV6 DNS
      # - https://[2001:4860:4860::6464]/dns-query #Google IPV6 DNS
      # - https://[2606:4700:4700::1111]/dns-query # Cloudflare
      # - https://[2606:4700:4700::1001]/dns-query # Cloudflare
      # - https://[2606:4700:4700::64]/dns-query # Cloudflare
      # - https://[2606:4700:4700::6464]/dns-query # Cloudflare 
    ## global，dns 为 rule-providers 中的名为 global 和 dns 规则订阅，
    ## 且 behavior 必须为 domain/classical，当为 classical 时仅会生效域名类规则 
    # "rule-set:global,dns": 8.8.8.8
  
  # 后备域名解析服务器，一般情况下使用境外 DNS, 保证结果可信;配置 fallback后默认启用 fallback-filter,geoip-code为 cn
  fallback:
      # 用来解析国外域名的dns，很多国内直接访问是有问题的
      # 国内能用且没有污染的dns      
      - https://dns.rubyfish.cn/dns-query # 红鱼rubyfish DNS  国外上游   
      - https://i.233py.com/dns-query # GEEKDNS 国内    
      - quic://cn-east.ovo.glass  # iQDNS 华东高防 BGP 节点
      - quic://cn-south.iqiqzz.com # iQDNS 华南高防 BGP 节点
      - https://cn-east.iqiqzz.com/dns-query # iQDNS 华东高防 BGP 节点
      - https://cn-south.iqiqzz.com/dns-query # iQDNS 华南高防 BGP 节点
      - https://doh.apad.pro/cn-query
      - https://doh.apad.pro/dns-query # apad.pro
      - https://doh.18bit.cn/dns-query # 18bit DNS
      # 用来解析国外域名的dns，很多国内直接访问是有问题的
      - https://dns.233py.com/dns-query # GEEKDNS 国外
      - https://dns.twnic.tw/dns-query # TWNIC Quad 101
      - https://public.dns.iij.jp/dns-query # 日本 IIJ DNS
      - https://doh-jp.blahdns.com/dns-query # 日本 Blahdns
      - https://doh.dns.sb/dns-query # DNS.SB 服务器位于国外，但延迟使用体检较为可观，支持 EDNS-Client-Subnet
      - quic://dns-unfiltered.adguard.com # AdGuard DNS
      - https://dns.cloudflare.com/dns-query # Cloudflare 公共DNS 国外
      - https://dns.google/dns-query # Google DNS
      - https://dns11.quad9.net/dns-query # IBM Quad9
      - https://doh.opendns.com/dns-query # OpenDNS
      - https://doh.powerdns.org # PowerDNS
      - https://dns.switch.ch/dns-quer #switch dns
      - https://private.canadianshield.cira.ca/dns-query #CIRA Canadian Shield DNS
      - https://all.dns.mullvad.net/dns-query # Mullvad Public DNS
      # ipv6 dns
      # - https://v6.rubyfish.cn/dns-query # 红鱼rubyfish IPV6 DNS
      - https://dns11.quad9.net/dns-query # IBM Quad9 ipv4+ipv6
      # - tls://[2a09::]:853 # DNS.SB 服务器位于国外，但延迟使用体检较为可观，支持 EDNS-Client-Subnet
      # - tls://[2a11::]:853 # DNS.SB 服务器位于国外，但延迟使用体检较为可观，支持 EDNS-Client-Subnet
      # - https://[2001:4860:4860::64]/dns-query #Google IPV6 DNS
      # - https://[2001:4860:4860::6464]/dns-query #Google IPV6 DNS
      # - https://[2606:4700:4700::1111]/dns-query # Cloudflare
      # - https://[2606:4700:4700::1001]/dns-query # Cloudflare
      # - https://[2606:4700:4700::64]/dns-query # Cloudflare
      # - https://[2606:4700:4700::6464]/dns-query # Cloudflare 
  fallback-filter: # 后备域名解析服务器筛选，满足条件的将使用 fallback结果或只使用 fallback解析
    geoip: true # 是否启用 fallback filter
    geoip-code: CN # 可选值为 国家缩写，默认值为 CN;除了 geoip-code 配置的国家 IP, 其他的 IP 结果会被视为污染;geoip-code 配置的国家的结果会直接采用，否则将采用 fallback结果
    geosite: # 对于的 geosite 内包含的集合,geosite 列表的内容被视为已污染，匹配到 geosite 的域名，将只使用 fallback解析，不去使用 nameserver
      - gfw
    ipcidr: # IP/掩码,这些网段的结果会被视为污染，nameserver解析出这些结果时将会采用 fallback的解析结果
      - 240.0.0.0/4
      - 0.0.0.0/8
      - 127.0.0.0/8
    domain: # 这些域名被视为已污染，匹配到这些域名，会直接使用 fallback解析，不去使用 nameserver
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
```
