### DISCUSSION TITLE
无法正常访问含cloudflare验证的网站

### DISCUSSION THREAD

**Discussion by cenaia** [libnyanpasu/clash-nyanpasu#850] [Q&A] [answered]
之前用的是mihomo内核，cloudflare一直打不开，切换成Clash Premium后好了一段时间
最近几天这个Clash Premium内核也不行了，其他内核也测试了，均无法测试通过，同订阅地址在手机clash上正常访问。
具体表现为cloudflare页面无限转圈圈，重载这个页面
使用隐私模式可以正常访问
我该检查哪些内容
测试浏览器：Win10 edge Chrome Firefox

**Comment by 4o3F** [comment]
既然隐私模式可以正常访问，那证明和clash无关

**Reply by cenaia** [reply]
> 既然隐私模式可以正常访问，那证明和clash无关

那有其他的解决方案吗

**Reply by greenhat616** [reply]
大抵是配置方面的问题，细节太少无法猜测。

**Reply by keiko233** [reply]
我猜猜是浏览器dns的问题，搭配fake ip+tun试试

**Reply by cenaia** [reply]
> 我猜猜是浏览器dns的问题，搭配fake ip+tun试试

正在使用fake-ip，但是TUN模式开启后CPU完全占用无法正常使用,我不知道哪里配置出现了问题，正在使用mihomo内核v.1.18.4

**Reply by cenaia** [reply]
> 我猜猜是浏览器dns的问题，搭配fake ip+tun试试

运行配置是这样的
```
mode: rule
mixed-port: 7890
allow-lan: true
log-level: info
ipv6: true
secret: ''
external-controller: 127.0.0.1:8381
dns:
  enable: true
  listen: 127.0.0.1:8853
  default-nameserver:
  - 223.5.5.5
  - 8.8.4.4
  ipv6: false
  enhanced-mode: fake-ip
  nameserver:
  - 119.29.29.29
  - 223.5.5.5
  - tls://223.5.5.5:853
  - tls://223.6.6.6:853
  - tls://120.53.53.53
  - tls://1.12.12.12
  fallback:
  - https://1.0.0.1/dns-query
  - https://public.dns.iij.jp/dns-query
  - tls://8.8.4.4:853
  fallback-filter:
    geoip: false
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
    - 127.0.0.1/32
    ```
