### ISSUE TITLE
TUN 模式 不是以配置文件为准么

### ISSUE THREAD

**Issue by toyo2333** [LibNyanpasu/clash-nyanpasu#1437]
### 复现步骤 / Step to reproduce

配置里写了
```
tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
```

启动后 运行时 里的 没有看到这段配置。

然后手工打开 软件里的 tun 开关

运行时里面变成了
```
tun:
  enable: true
  stack: gvisor
  dns-hijack:
  - any:53
  auto-route: true
  auto-detect-interface: true
```

### 预期行为 / Expected behaviour

应该以配置文件为准

### 实际行为 / Actual Behaviour

实际上，配置文件里的项目没生效。

### 备注 / Addition details

拿到不支持配置文件的方式开启tun？

### 环境信息 / Environment information

当前正式版的最新版

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version
