### ISSUE TITLE
BUG-仅开启“TUN模式”时 存在DNS泄露，但开了系统代理则不会

### ISSUE THREAD

**Issue by toyo2333** [libnyanpasu/clash-nyanpasu#1440]
### 复现步骤 / Step to reproduce

1、win11，管理员权限运行程序，然后打开“TUN模式”（但不勾选“系统代理”）；
2、完成后，开启全局代理模式，浏览器打开 https://ipleak.net/ 和 https://browserleaks.com/dns 这两个测试站点
3、完成测试后，观察2个不同测试工具的测试结果

### 预期行为 / Expected behaviour

测试结果里不应该出现 本地运营商的 DNS 服务器IP （即不出现DNS泄露）---应该全部仅是远端服务器的出口IP的  DNS 服务器

### 实际行为 / Actual Behaviour

出现了本地运营商的 DNS 服务器 IP （意味着 DNS 泄露）。

作为对比：如果关闭“ TUN 模式”，打开  “系统代理” ，测试结果正常 则不会出现本地 本地运营商的 DNS 服务器 IP（DNS 泄露），如果 同时打开 “ TUN 模式” 和 “系统代理”  也没问题。问题值出现在 仅开启  “ TUN 模式” 时候

### 应用日志 / App logs

没有找到日志，但可以必然复现，以下是配置文件里 DNS 和 TUN 的配置：
```
tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

dns:
  enable: true
  prefer-h3: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
  nameserver:
    - https://1.12.12.12/dns-query
    - https://223.5.5.5/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - https://1.12.12.12/dns-query
      - https://223.5.5.5/dns-query
```

### 环境信息 / Environment information

clash 内核  是 meta v1.18.7 meta
clash客户端是：Clash Nyanpasu 1.5.1 
系统 win11 最新版

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version
