### ISSUE TITLE
请求支持TUN模式的严格路由

### ISSUE THREAD

**Issue by Alexius66** [libnyanpasu/clash-nyanpasu#1501]
### 需求 / Requirement

TUN在我的配置里：
```
tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  strict-route: true
  dns-hijack:
  - any:53
  - tcp://any:53
```

在运行时配置中会被改写为：

```
tun:
  enable: true
  stack: mixed
  dns-hijack:
  - any:53
  auto-route: true
  auto-detect-interface: true
```
我希望可以支持严格路由的开启，我知道理论上可以通过禁用智能多宿主解析来实现相同的效果，但实际上如果开启ipv6的话禁用智能多宿主解析仍然会导致dns泄露。

### 建议实现 / Suggested implements

只需要不修改用户配置就可以实现

### 备注 / Addition details

另外还想问一下为什么TUN中dns-hijack这一项也会被强制修改？mihomo官方文档快捷配置中的
```
  dns-hijack:
    - any:53
    - tcp://any:53
 ```
会被改写为
```
  dns-hijack:
  - any:53
```

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.6.0

### 是否为 Pre-release / Is pre-release version

否

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version
