### ISSUE TITLE
无法使用配置文件内置的仪表盘，

### ISSUE THREAD

**Issue by Kwisma** [libnyanpasu/clash-nyanpasu#2310]
### 复现步骤 / Step to reproduce

配置文件
```yaml
external-controller: 0.0.0.0:1234
external-ui: 5465674
external-ui-url: "地址" 
```
导入没有开启配置文件内的外部控制端口

无法访问 127.0.0.1:1234

### 预期行为 / Expected behavior

配置文件
```yaml
external-controller: 0.0.0.0:1234
external-ui: 5465674
external-ui-url: "地址" 
```
导入开启配置文件内的外部控制端口

正常访问 127.0.0.1:1234/

### 实际行为 / Actual behavior

开启配置文件内的外部控制端口

### 备注 / Addition details

软件的内置的外部控制端口只能通过指定的域名访问，这不是我想要的

### 环境信息 / Environment information

window11
Clash Nyanpasu v1.6.1
mihomo v1.18.8

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日志，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues) and [FAQ](https://nyanpasu.elaina.moe/others/faq)
- [X] 您已搜索过 [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make multiply issue for multiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version
