### ISSUE TITLE
配置文件中速度测试地址配置失效

### ISSUE THREAD

**Issue by utopeadia** [LibNyanpasu/clash-nyanpasu#541]
### 复现步骤 / Step to reproduce

在规则文件中，不同分组使用不同的测速地址（比如某些访问特定内网的节点测试会使用内网地址，而用来过墙的节点测试使用谷歌或者其他地址），但是在GUI中从延迟看某些分组的测速地址被强制修改为其他地址了

### 预期行为 / Expected behaviour

不同分组测速地址不同

### 实际行为 / Actual Behaviour

使用了相同的测速地址

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.5

### 是否为 Pre-release / Is pre-release version

NO

### 操作系统及版本 / OS version

win11

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
可能需要提供一份样例配置文件供测试使用

**Comment by utopeadia** [comment]
> 可能需要提供一份样例配置文件供测试使用

比如说我会在自家路由器搭建一个ss服务器作为“回家节点”用于在外访问家里的nas等设备，同时也会有科学节点用于科学，我配置了形如：
```YAML
- name: 主要代理
    type: url-test
    url: https://google.com
    interval: 30
    tolerance: 5
    proxies:
      - ‍代理1
      - ‍代理2
- name: 回家专用测速
    type: url-test
    url: http://192.168.66.66
    interval: 30
    tolerance: 5
    proxies:
      - ‍回家自建转发SS
      - DIRECT
```
当两个节点的url-test url不同时，我发现点击测速回家测速也使用了代理用的测速地址

**Comment by keiko233** [comment]
> > 可能需要提供一份样例配置文件供测试使用
> 
> 比如说我会在自家路由器搭建一个ss服务器作为“回家节点”用于在外访问家里的nas等设备，同时也会有科学节点用于科学，我配置了形如：
> 
> ```yaml
> - name: 主要代理
>     type: url-test
>     url: https://google.com
>     interval: 30
>     tolerance: 5
>     proxies:
>       - ‍代理1
>       - ‍代理2
> - name: 回家专用测速
>     type: url-test
>     url: http://192.168.66.66
>     interval: 30
>     tolerance: 5
>     proxies:
>       - ‍回家自建转发SS
>       - DIRECT
> ```
> 
> 当两个节点的url-test url不同时，我发现点击测速回家测速也使用了代理用的测速地址

查了一下，指定节点的url似乎不是内核的标准提案，目前官方给到的只有代理组的url
https://wiki.metacubex.one/config/proxy-groups/#url

**Comment by utopeadia** [comment]
> > > 可能需要提供一份样例配置文件供测试使用
> > 
> > 
> > 比如说我会在自家路由器搭建一个ss服务器作为“回家节点”用于在外访问家里的nas等设备，同时也会有科学节点用于科学，我配置了形如：
> > ```yaml
> > - name: 主要代理
> >     type: url-test
> >     url: https://google.com
> >     interval: 30
> >     tolerance: 5
> >     proxies:
> >       - ‍代理1
> >       - ‍代理2
> > - name: 回家专用测速
> >     type: url-test
> >     url: http://192.168.66.66
> >     interval: 30
> >     tolerance: 5
> >     proxies:
> >       - ‍回家自建转发SS
> >       - DIRECT
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 当两个节点的url-test url不同时，我发现点击测速回家测速也使用了代理用的测速地址
> 
> 查了一下，指定节点的url似乎不是内核的标准提案，目前官方给到的只有代理组的url https://wiki.metacubex.one/config/proxy-groups/#url https://watfaq.github.io/clash-rs/clash_doc/struct.ClashConfigDef.html# ![image](https://private-user-images.githubusercontent.com/76520798/348061348-0285bd5a-27df-4376-a0cd-d4dbc6d290fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NDk0NDAsIm5iZiI6MTcyMDc0OTE0MCwicGF0aCI6Ii83NjUyMDc5OC8zNDgwNjEzNDgtMDI4NWJkNWEtMjdkZi00Mzc2LWEwY2QtZDRkYmM2ZDI5MGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDAxNTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNmM5ZGNiNjI3ZDgyMGRiNDU4YTc0MjhkMDRiZWY1NGI0ODI2ZWM0ZTcxYTI2OTY0NDdiOWE4Mjg2YjUyZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ttU29oc2avMwyegDxx024XRQWIr4_ylgjDxlZ3EE0MI)

您的意思是每一个proxy-groups下对应一个测试url吗，mihomo的demo中只给了一个策略的情形，我注意到clash rs的文档里面也是这种使用方法，即每一个url-test的组下面都会设置一个url
```
proxy-groups:
  - name: "relay"
    type: relay
    proxies:
      - "plain-vmess"
      - "ws-vmess"
      - "auto"
      - "fallback-auto"
      - "load-balance"
      - "select"
      - DIRECT
  - name: "relay-one"
    type: relay
    use:
      - "file-provider"
  - name: "auto"
    type: url-test
    use:
      - "file-provider"
    proxies:
      - DIRECT
    url: "http://www.gstatic.com/generate_204"
    interval: 300
  - name: "fallback-auto"
    type: fallback
    use:
      - "file-provider"
    proxies:
      - DIRECT
    url: "http://www.gstatic.com/generate_204"
    interval: 300
```
只是在他们的文档中url都使用的相同的地址
我的配置类似：
```
proxy-groups:
  - name: 主要代理
      type: url-test
      url: https://google.com
      interval: 30
      tolerance: 5
      proxies:
        - ‍代理1
        - ‍代理2

  - name: 回家专用测速
      type: url-test
      url: http://192.168.66.66
      interval: 30
      tolerance: 5
      proxies:
        - ‍回家自建转发SS
        - DIRECT
```
