### ISSUE TITLE
[BUG] 配置tunnels或relay的落地节点经常无法ping通

### ISSUE THREAD

**Issue by stimw** [LibNyanpasu/clash-nyanpasu#98]
**Describe the bug**
- 配置tunnels或relay的落地节点经常无法ping通，见下面截图和配置文件
- 虽然显示无法ping通但是可以正常使用，并且机场节点没有出现这个问题

以上问题在clash verge rev中，使用同一配置文件，没有复现。（已关闭clash过滤字段）

**To Reproduce**
可以尝试确认任意tunnels或relay配置能否总是正常ping通

**Expected behavior**
正常ping通

**Screenshots**
<img width="795" alt="image" src="https://github.com/keiko233/clash-nyanpasu/assets/30977647/14432c36-a55b-4259-add7-c1a8fd4257d8">

**Information**

- OS: macOS
- Clash Nyanpasu Version: 1.4.1
- Clash Core: Clash Meta

**Additional context**

Simple Config:
```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
tunnels:
  - network: [tcp, udp]
    address: 127.0.0.1:7777
    target:  # 手动打码
    proxy: Kuromi
proxies:
  - name: 'singapore-ss'
    type: ss
    server: 127.0.0.1
    port: 7777
    cipher: # 手动打码
    password:  # 手动打码
proxy-providers:
  Jichang:
    type: http
    url:  # 手动打码
    path: ./Proxy/Jichang.yml
    interval: 86400
    health-check:
      enable: false
      interval: 600
      url: https://www.gstatic.com/generate_204
proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - singapore-ss
      - DIRECT
  - name: Kuromi
    type: select
    use:
      - Jichang
```

**Information**

- OS: macOS
- Clash Nyanpasu Version: 1.4.1
- Clash Core: Clash Meta
